export const STORY_CATEGORIES = [
  "Uncategorized",
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Thriller",
  "Horror",
  "Adventure",
  "Historical Fiction",
  // Blockchain & Web3 inspired genres
  "Cyberpunk",
  "Techno-thriller",
  "Dystopian",
  "Blockchain",
  "Crypto",
  "Web3",
  "DeFi",
  "DAO",
  "NFT",
  // AO-focused narrative genres
  "AO Chronicles",
  "Immutable Realms",
  "Arweave Odyssey",
  "Decentralized Legends",
  "Protocol Parables",
  "Smart Contract Stories",
  "Token Tales",
  // Education & Technology categories inspired by AO and Arweave ecosystem
  "Arweave Academy",
  "AO Dev Workshops",
  "Decentralized Programming",
  "Tech Stack Tutorials",
  "Smart Contract Education",
  "Blockchain Bootcamp",
  "Coding Chronicles",
  "TypeScript Tutorials",
  "Lua Lessons",
  "Erlang Essentials",
  "APM Insights",
  "Open Source Odyssey",
  "Protocol Programming",
  "Infrastructure Innovations",
  "Permanent Web Development"
] as const;
