export const STORY_CATEGORIES = [
  "Uncategorized",
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Thriller",
  "Horror",
  "Adventure",
  "Historical Fiction",
  "Permaweb",
  "AO Legacynet",
  "AO CORE",
  "BazAR",
  "Arweave",
  "ArNS",
  "ARIO Gateways",
  "SDKs",
  "Libraries",
  "Tools",
  "Tutorials",
  "Documentation",
  "Community",
  "HyperBEAM",
  "Weavers",
  "Other"
] as const;
